"""Typed models of the RPG_RT.ldb database tables.

Database files exported by rpgsync (``Scripts/database/*.py``) hold these models (see rpgsync.tables).
Defaults are liblcf's; a keyword left out of a file means the default value.

Generated by tools/gen_dbschema.py from liblcf's generator/csv; do not edit.
"""


from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, PrivateAttr

__all__ = [
    "Actor",
    "Attribute",
    "AttributeType",
    "BattlerAnimation",
    "BattlerAnimationItemSkill",
    "BattlerAnimationItemSkillAfterimage",
    "BattlerAnimationItemSkillAnimType",
    "BattlerAnimationItemSkillMovement",
    "BattlerAnimationItemSkillSpeed",
    "BattlerAnimationPose",
    "BattlerAnimationPoseAnimType",
    "BattlerAnimationSpeed",
    "BattlerAnimationWeapon",
    "Class",
    "DbModel",
    "Enemy",
    "EnemyAction",
    "EnemyActionBasic",
    "EnemyActionConditionType",
    "EnemyActionKind",
    "Equipment",
    "Item",
    "ItemTarget",
    "ItemTrajectory",
    "ItemType",
    "Learning",
    "Parameters",
    "Skill",
    "SkillScope",
    "SkillSpType",
    "SkillType",
    "Sound",
    "State",
    "StateAffectType",
    "StateChangeType",
    "StatePersistence",
    "StateRestriction",
    "Switch",
    "Terrain",
    "TerrainBGAssociation",
    "TerrainBushDepth",
    "TerrainFlags",
    "Troop",
    "TroopMember",
    "Variable",
]


def _freeze(v: Any) -> Any:
    if isinstance(v, dict):
        return tuple((k, _freeze(x)) for k, x in v.items())
    if isinstance(v, (list, tuple)):
        return tuple(_freeze(x) for x in v)
    return v


class DbModel(BaseModel):
    """Base class of the database models."""
    model_config = ConfigDict(extra="forbid")
    _lineno: int | None = PrivateAttr(default=None)
    _ident: str | None = PrivateAttr(default=None)

    @property
    def lineno(self) -> int | None:
        """Line of the entry in its database file (None when read from the game)."""
        return self._lineno

    def key(self) -> tuple:
        """Hashable value used to compare entries."""
        return _freeze(self.model_dump())


BattlerAnimationItemSkillAnimType = Literal["weapon", "battle"]
BattlerAnimationItemSkillMovement = Literal["none", "step", "jump", "move"]
BattlerAnimationItemSkillAfterimage = Literal["none", "add"]
BattlerAnimationItemSkillSpeed = Literal["fast", "medium", "slow"]
SkillType = Literal["normal", "teleport", "escape", "switch", "subskill"]
SkillSpType = Literal["cost", "percent"]
SkillScope = Literal["enemy", "enemies", "self", "ally", "party"]
ItemType = Literal[
    "normal",
    "weapon",
    "shield",
    "armor",
    "helmet",
    "accessory",
    "medicine",
    "book",
    "material",
    "special",
    "switch",
]
ItemTrajectory = Literal["straight", "return"]
ItemTarget = Literal["single", "center", "simultaneous", "sequential"]
EnemyActionKind = Literal["basic", "skill", "transformation"]
EnemyActionBasic = Literal[
    "attack",
    "dual_attack",
    "defense",
    "observe",
    "charge",
    "autodestruction",
    "escape",
    "nothing",
]
EnemyActionConditionType = Literal[
    "always",
    "switch",
    "turn",
    "actors",
    "hp",
    "sp",
    "party_lvl",
    "party_fatigue",
]
StatePersistence = Literal["ends", "persists"]
StateRestriction = Literal["normal", "do_nothing", "attack_enemy", "attack_ally"]
StateAffectType = Literal["half", "double", "nothing"]
StateChangeType = Literal["lose", "gain", "nothing"]
AttributeType = Literal["physical", "magical"]
TerrainBushDepth = Literal["normal", "third", "half", "full"]
TerrainBGAssociation = Literal["background", "frame"]
BattlerAnimationPoseAnimType = Literal["character", "battle"]
BattlerAnimationSpeed = Literal["slow", "medium", "fast"]


class TerrainFlags(DbModel):
    """Bit flags Terrain."""
    back_party: bool = Field(default=False, description="Back party. RPG Maker 2003 only.")
    back_enemies: bool = Field(default=False, description="Back enemies. RPG Maker 2003 only.")
    lateral_party: bool = Field(default=False, description="Lateral party. RPG Maker 2003 only.")
    lateral_enemies: bool = Field(default=False, description="Lateral enemies. RPG Maker 2003 only.")


class Parameters(DbModel):
    """Base stats per level: element N-1 of each list is the value at level N."""

    maxhp: list[int] = Field(default_factory=list, description="Maxhp.")
    maxsp: list[int] = Field(default_factory=list, description="Maxsp.")
    attack: list[int] = Field(default_factory=list, description="Attack.")
    defense: list[int] = Field(default_factory=list, description="Defense.")
    spirit: list[int] = Field(default_factory=list, description="Spirit.")
    agility: list[int] = Field(default_factory=list, description="Agility.")


class Equipment(DbModel):
    """Initial equipment: item ids, 0 = nothing."""

    weapon_id: int = Field(default=0, description="Weapon id (item id).")
    shield_id: int = Field(default=0, description="Shield id (item id).")
    armor_id: int = Field(default=0, description="Armor id (item id).")
    helmet_id: int = Field(default=0, description="Helmet id (item id).")
    accessory_id: int = Field(default=0, description="Accessory id (item id).")


class Learning(DbModel):
    """A skill learned at a given level."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    level: int = Field(default=1, description="Level at which the skill is learned.")
    skill_id: int = Field(default=1, description="Learned skill (skill id).")


class Actor(DbModel):
    """A hero (Database > Actors)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    title: str = Field(default="", description="Title shown under the name (e.g. 'Knight').")
    character_name: str = Field(default="", description="CharSet file used on the map.")
    character_index: int = Field(default=0, description="Sprite index (0-7) inside the CharSet.")
    transparent: bool = Field(default=False, description="Draw the map sprite translucent.")
    initial_level: int = Field(default=1, description="Level when joining the party.")
    final_level: int | None = Field(
        default=None,
        description=(
            "Maximum level. None = the engine default (50 in RPG Maker 2000, 99 in RPG Maker "
            "2003)."
        ),
    )
    critical_hit: bool = Field(default=True, description="Can land critical hits.")
    critical_hit_chance: int = Field(default=30, description="Critical hit probability: 1 in N.")
    face_name: str = Field(default="", description="FaceSet file.")
    face_index: int = Field(default=0, description="Face index (0-15) inside the FaceSet.")
    two_weapon: bool = Field(
        default=False,
        description="Wields two weapons instead of weapon + shield.",
    )
    lock_equipment: bool = Field(default=False, description="Equipment cannot be changed.")
    auto_battle: bool = Field(default=False, description="Fights automatically.")
    super_guard: bool = Field(
        default=False,
        description="Strong defense (damage quartered when defending).",
    )
    parameters: Parameters = Field(
        default_factory=Parameters,
        description="Max HP/SP, attack, defense, spirit and agility per level.",
    )
    exp_base: int | None = Field(
        default=None,
        description=(
            "Experience curve: base value. None = the engine default (30 in RPG Maker 2000, 300 "
            "in RPG Maker 2003)."
        ),
    )
    exp_inflation: int | None = Field(
        default=None,
        description=(
            "Experience curve: inflation. None = the engine default (30 in RPG Maker 2000, 300 in "
            "RPG Maker 2003)."
        ),
    )
    exp_correction: int = Field(default=0, description="Experience curve: correction.")
    initial_equipment: Equipment = Field(
        default_factory=Equipment,
        description="Equipment when joining the party.",
    )
    unarmed_animation: int = Field(
        default=1,
        description="Battle animation of unarmed attacks (battle animation id).",
    )
    class_id: int = Field(default=0, description="Class (class id). RPG Maker 2003 only.")
    battle_x: int = Field(default=220, description="Battle position X. RPG Maker 2003 only.")
    battle_y: int = Field(default=120, description="Battle position Y. RPG Maker 2003 only.")
    battler_animation: int = Field(
        default=1,
        description="Battler animation (battle charset; battler animation id). RPG Maker 2003 only.",
    )
    skills: list[Learning] = Field(default_factory=list, description="Skills learned by level.")
    rename_skill: bool = Field(
        default=False,
        description="Use a custom name for the Skill battle command.",
    )
    skill_name: str = Field(default="", description="Custom name of the Skill battle command.")
    state_ranks: list[int] = Field(
        default_factory=list,
        description="State ranks (rank per state id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    attribute_ranks: list[int] = Field(
        default_factory=list,
        description="Attribute ranks (rank per attribute id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    battle_commands: list[int] = Field(
        default_factory=list,
        description="Battle command ids (-1 = none). RPG Maker 2003 only.",
    )
    easyrpg_actorai: int = Field(
        default=-1,
        description=(
            "Default autobattle AI behavior of the actor with 0=RPG_RT 1=RPG_RT+ 2=ATTACK. "
            "EasyRPG Player extension."
        ),
    )
    easyrpg_prevent_critical: bool = Field(
        default=False,
        description="If the actor is protected against critical hits. EasyRPG Player extension.",
    )
    easyrpg_raise_evasion: bool = Field(
        default=False,
        description="If the actor has an increased evasion rate. EasyRPG Player extension.",
    )
    easyrpg_immune_to_attribute_downshifts: bool = Field(
        default=False,
        description="If the actor is immune to attribute downshifts. EasyRPG Player extension.",
    )
    easyrpg_ignore_evasion: bool = Field(
        default=False,
        description=(
            "If the actors unarmed physical attacks ignore evasion. EasyRPG Player extension."
        ),
    )
    easyrpg_unarmed_hit: int = Field(
        default=-1,
        description="Hit rate of the actor on unarmed attacks. EasyRPG Player extension.",
    )
    easyrpg_unarmed_state_set: list[bool] = Field(
        default_factory=list,
        description=(
            "States inflicted by unarmed normal attacks of the actor (one flag per state id, "
            "index 0 is id 1). EasyRPG Player extension."
        ),
    )
    easyrpg_unarmed_state_chance: int = Field(
        default=0,
        description=(
            "State infliction probability by unarmed normal attacks of the actor. EasyRPG Player "
            "extension."
        ),
    )
    easyrpg_unarmed_attribute_set: list[bool] = Field(
        default_factory=list,
        description=(
            "Attributes used by unarmed normal attacks of the actor (one flag per attribute id, "
            "index 0 is id 1). EasyRPG Player extension."
        ),
    )
    easyrpg_dual_attack: bool = Field(
        default=False,
        description="If the actors unarmed physical attacks hits twice. EasyRPG Player extension.",
    )
    easyrpg_attack_all: bool = Field(
        default=False,
        description=(
            "If the actors unarmed physical targets the entire enemy party. EasyRPG Player "
            "extension."
        ),
    )


class Class(DbModel):
    """A character class (Database > Classes, RPG Maker 2003)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    two_weapon: bool = Field(default=False, description="Two weapon.")
    lock_equipment: bool = Field(default=False, description="Lock equipment.")
    auto_battle: bool = Field(default=False, description="Auto battle.")
    super_guard: bool = Field(default=False, description="Super guard.")
    parameters: Parameters = Field(
        default_factory=Parameters,
        description="Max HP/SP, attack, defense, spirit and agility per level.",
    )
    exp_base: int = Field(default=300, description="Exp base.")
    exp_inflation: int = Field(default=300, description="Exp inflation.")
    exp_correction: int = Field(default=0, description="Exp correction.")
    battler_animation: int = Field(
        default=0,
        description="Battler animation (battle charset; battle animation id).",
    )
    skills: list[Learning] = Field(default_factory=list, description="Skills learned by level.")
    state_ranks: list[int] = Field(
        default_factory=list,
        description="State ranks (rank per state id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    attribute_ranks: list[int] = Field(
        default_factory=list,
        description="Attribute ranks (rank per attribute id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    battle_commands: list[int] = Field(
        default_factory=list,
        description="Battle command ids (-1 = none).",
    )


class Sound(DbModel):
    """A sound effect."""

    name: str = Field(default="(OFF)", description="File in Sound/ ('(OFF)' = none).")
    volume: int = Field(default=100, description="Volume in percent.")
    tempo: int = Field(default=100, description="Tempo in percent.")
    balance: int = Field(default=50, description="Balance (0 = left, 50 = center, 100 = right).")


class BattlerAnimationItemSkill(DbModel):
    """How one actor animates when using a weapon or skill (RPG Maker 2003)."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    unknown02: int = Field(default=0, description="Unknown02. RPG Maker 2003 only.")
    type: BattlerAnimationItemSkillAnimType | int = Field(
        default="weapon",
        description="Type (one of 'weapon', 'battle' or a number). RPG Maker 2003 only.",
    )
    weapon_animation_id: int = Field(
        default=0,
        description="Weapon animation id (battler animation weapon id). RPG Maker 2003 only.",
    )
    movement: BattlerAnimationItemSkillMovement | int = Field(
        default="none",
        description=(
            "Movement (one of 'none', 'step', 'jump', 'move' or a number). RPG Maker 2003 only."
        ),
    )
    after_image: BattlerAnimationItemSkillAfterimage | int = Field(
        default="none",
        description="After image (one of 'none', 'add' or a number). RPG Maker 2003 only.",
    )
    attacks: int = Field(default=0, description="Attacks. RPG Maker 2003 only.")
    ranged: bool = Field(default=False, description="Ranged. RPG Maker 2003 only.")
    ranged_animation_id: int = Field(
        default=0,
        description="Ranged animation id (battler animation weapon id). RPG Maker 2003 only.",
    )
    ranged_speed: BattlerAnimationItemSkillSpeed | int = Field(
        default="fast",
        description=(
            "Ranged speed (one of 'fast', 'medium', 'slow' or a number). RPG Maker 2003 only."
        ),
    )
    battle_animation_id: int = Field(
        default=1,
        description="Battle animation id (battle animation id). RPG Maker 2003 only.",
    )
    pose: int = Field(
        default=3,
        description="Pose (battler animation pose id). RPG Maker 2003 only.",
    )


class Skill(DbModel):
    """A skill (Database > Skills)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    description: str = Field(default="", description="Help text.")
    using_message1: str = Field(
        default="",
        description="Battle message when used (first line). RPG Maker 2000 only.",
    )
    using_message2: str = Field(
        default="",
        description="Battle message when used (second line). RPG Maker 2000 only.",
    )
    failure_message: int = Field(
        default=0,
        description="Message shown when the skill fails. RPG Maker 2000 only.",
    )
    type: SkillType | int = Field(
        default="normal",
        description=(
            "Type (one of 'normal', 'teleport', 'escape', 'switch', 'subskill' or a number)."
        ),
    )
    sp_type: SkillSpType | int = Field(
        default="cost",
        description="SP cost unit (one of 'cost', 'percent' or a number). RPG Maker 2003 only.",
    )
    sp_percent: int = Field(
        default=0,
        description="SP cost in percent of max SP. RPG Maker 2003 only.",
    )
    sp_cost: int = Field(default=0, description="SP cost.")
    scope: SkillScope | int = Field(
        default="enemy",
        description="Target (one of 'enemy', 'enemies', 'self', 'ally', 'party' or a number).",
    )
    switch_id: int = Field(default=1, description="Switch turned ON by switch skills (switch id).")
    animation_id: int = Field(default=1, description="Battle animation (battle animation id).")
    sound_effect: Sound = Field(
        default_factory=Sound,
        description="Sound of teleport/escape/switch skills.",
    )
    occasion_field: bool = Field(default=True, description="Usable on the map.")
    occasion_battle: bool = Field(default=False, description="Usable in battle.")
    reverse_state_effect: bool = Field(
        default=False,
        description="Inflict the states instead of curing them. RPG Maker 2003 only.",
    )
    physical_rate: int = Field(default=0, description="Attack influence (0-10).")
    magical_rate: int = Field(default=3, description="Spirit influence (0-10).")
    variance: int = Field(default=4, description="Damage variance (0-10).")
    power: int = Field(default=0, description="Base effect value.")
    hit: int = Field(default=100, description="Success rate in percent.")
    affect_hp: bool = Field(default=False, description="Affect hp.")
    affect_sp: bool = Field(default=False, description="Affect sp.")
    affect_attack: bool = Field(default=False, description="Affect attack.")
    affect_defense: bool = Field(default=False, description="Affect defense.")
    affect_spirit: bool = Field(default=False, description="Affect spirit.")
    affect_agility: bool = Field(default=False, description="Affect agility.")
    absorb_damage: bool = Field(default=False, description="Absorb the damage.")
    ignore_defense: bool = Field(default=False, description="Ignore the target's defense.")
    state_effects: list[bool] = Field(
        default_factory=list,
        description="States changed by the skill (one flag per state id, index 0 is id 1).",
    )
    attribute_effects: list[bool] = Field(
        default_factory=list,
        description="Attributes of the skill (one flag per attribute id, index 0 is id 1).",
    )
    affect_attr_defence: bool = Field(
        default=False,
        description="Lower the target's resistance to the attributes.",
    )
    battler_animation: int = Field(
        default=-1,
        description="Battler animation used (actor id). RPG Maker 2003 only.",
    )
    battler_animation_data: list[BattlerAnimationItemSkill] = Field(
        default_factory=list,
        description="Battle animation settings per actor. RPG Maker 2003 only.",
    )
    easyrpg_battle2k3_message: str = Field(
        default="default_message",
        description=(
            "RPG Maker 2003 battle skill start notification. RPG Maker 2003 only. EasyRPG Player "
            "extension."
        ),
    )
    easyrpg_ignore_reflect: bool = Field(
        default=False,
        description=(
            "If the skill bypasses reflect states. Useful for physical skills and skills which "
            "are meant to remove positive states from enemies. RPG Maker 2003 only. EasyRPG "
            "Player extension."
        ),
    )
    easyrpg_state_hit: int = Field(
        default=-1,
        description="Separate accuracy value for state inflictions. EasyRPG Player extension.",
    )
    easyrpg_attribute_hit: int = Field(
        default=-1,
        description="Separate accuracy value for attribute shifts. EasyRPG Player extension.",
    )
    easyrpg_ignore_restrict_skill: bool = Field(
        default=False,
        description=(
            "If the skill should bypass skill restrictions by states. EasyRPG Player extension."
        ),
    )
    easyrpg_ignore_restrict_magic: bool = Field(
        default=False,
        description=(
            "If the skill should bypass magic restrictions by states. EasyRPG Player extension."
        ),
    )
    easyrpg_enable_stat_absorbing: bool = Field(
        default=False,
        description=(
            "If the skill can absorb attack/defense/spirit/agility. EasyRPG Player extension."
        ),
    )
    easyrpg_affected_by_evade_all_physical_attacks: bool = Field(
        default=False,
        description=(
            "If the skill should be affected by avoid attack states. RPG Maker 2003 only. EasyRPG "
            "Player extension."
        ),
    )
    easyrpg_critical_hit_chance: int = Field(
        default=0,
        description=(
            "Critical hit rate percentage for the skill. If negative then the battler critical "
            "hit rate is used. EasyRPG Player extension."
        ),
    )
    easyrpg_affected_by_row_modifiers: bool = Field(
        default=False,
        description=(
            "If the skill is affected by row modifiers. RPG Maker 2003 only. EasyRPG Player "
            "extension."
        ),
    )
    easyrpg_hp_type: SkillSpType | int = Field(
        default="cost",
        description=(
            "If the HP usage of the skill is a fixed number or in percent of the maximum HP (one "
            "of 'cost', 'percent' or a number). RPG Maker 2003 only. EasyRPG Player extension."
        ),
    )
    easyrpg_hp_percent: int = Field(
        default=0,
        description=(
            "How much percent of the maximum HP does the usage of the skill cost. RPG Maker 2003 "
            "only. EasyRPG Player extension."
        ),
    )
    easyrpg_hp_cost: int = Field(
        default=0,
        description="How much HP does the usage of the skill cost. EasyRPG Player extension.",
    )


class Item(DbModel):
    """An item, weapon or armor (Database > Items)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    description: str = Field(default="", description="Help text.")
    type: ItemType | int = Field(
        default="normal",
        description=(
            "Type (one of 'normal', 'weapon', 'shield', 'armor', 'helmet', 'accessory', "
            "'medicine', 'book', 'material', 'special', 'switch' or a number)."
        ),
    )
    price: int = Field(default=0, description="Shop price.")
    uses: int = Field(default=1, description="Number of uses (0 = unlimited).")
    atk_points1: int = Field(default=0, description="Attack bonus (equipment).")
    def_points1: int = Field(default=0, description="Defense bonus (equipment).")
    spi_points1: int = Field(default=0, description="Spirit bonus (equipment).")
    agi_points1: int = Field(default=0, description="Agility bonus (equipment).")
    two_handed: bool = Field(default=False, description="Two-handed weapon.")
    sp_cost: int = Field(default=0, description="SP consumed per attack.")
    hit: int = Field(default=90, description="Hit rate in percent.")
    critical_hit: int = Field(default=0, description="Critical hit bonus in percent.")
    animation_id: int = Field(default=1, description="Battle animation (battle animation id).")
    preemptive: bool = Field(default=False, description="Attack first.")
    dual_attack: bool = Field(default=False, description="Attack twice.")
    attack_all: bool = Field(default=False, description="Attack all enemies.")
    ignore_evasion: bool = Field(default=False, description="Ignore evasion.")
    prevent_critical: bool = Field(default=False, description="Prevent critical hits.")
    raise_evasion: bool = Field(default=False, description="Raise evasion.")
    half_sp_cost: bool = Field(default=False, description="Halve SP costs.")
    no_terrain_damage: bool = Field(default=False, description="No terrain damage.")
    cursed: bool = Field(
        default=False,
        description="Cursed (cannot be unequipped). RPG Maker 2003 only.",
    )
    entire_party: bool = Field(default=False, description="Medicine affects the entire party.")
    recover_hp_rate: int = Field(default=0, description="HP recovered in percent.")
    recover_hp: int = Field(default=0, description="HP recovered.")
    recover_sp_rate: int = Field(default=0, description="SP recovered in percent.")
    recover_sp: int = Field(default=0, description="SP recovered.")
    occasion_field1: bool = Field(default=False, description="Medicine usable on the map only.")
    ko_only: bool = Field(default=False, description="Only usable on knocked out actors.")
    max_hp_points: int = Field(default=0, description="Max HP increase (books/material).")
    max_sp_points: int = Field(default=0, description="Max SP increase (books/material).")
    atk_points2: int = Field(default=0, description="Attack increase (books/material).")
    def_points2: int = Field(default=0, description="Defense increase (books/material).")
    spi_points2: int = Field(default=0, description="Spirit increase (books/material).")
    agi_points2: int = Field(default=0, description="Agility increase (books/material).")
    using_message: int = Field(default=0, description="Message shown when used (0 = default).")
    skill_id: int = Field(default=1, description="Skill invoked by special items (skill id).")
    switch_id: int = Field(default=1, description="Switch turned ON by switch items (switch id).")
    occasion_field2: bool = Field(default=True, description="Switch item usable on the map.")
    occasion_battle: bool = Field(default=False, description="Switch item usable in battle.")
    actor_set: list[bool] = Field(
        default_factory=list,
        description="Actors who can use/equip the item (one flag per actor id, index 0 is id 1).",
    )
    state_set: list[bool] = Field(
        default_factory=list,
        description="States changed by the item (one flag per state id, index 0 is id 1).",
    )
    attribute_set: list[bool] = Field(
        default_factory=list,
        description="Attributes of the item (one flag per attribute id, index 0 is id 1).",
    )
    state_chance: int = Field(default=0, description="State change probability in percent.")
    reverse_state_effect: bool = Field(
        default=False,
        description="Inflict the states instead of curing them.",
    )
    weapon_animation: int = Field(
        default=-1,
        description="Weapon animation (actor id). RPG Maker 2003 only.",
    )
    animation_data: list[BattlerAnimationItemSkill] = Field(
        default_factory=list,
        description="Battle animation settings per actor. RPG Maker 2003 only.",
    )
    use_skill: bool = Field(
        default=False,
        description="Weapon/armor invokes its skill when used. RPG Maker 2003 only.",
    )
    class_set: list[bool] = Field(
        default_factory=list,
        description=(
            "Classes who can use/equip the item (one flag per class id, index 0 is id 1). RPG "
            "Maker 2003 only."
        ),
    )
    ranged_trajectory: ItemTrajectory | int = Field(
        default="straight",
        description="Trajectory of ranged weapons (one of 'straight', 'return' or a number).",
    )
    ranged_target: ItemTarget | int = Field(
        default="single",
        description=(
            "Target of ranged weapons (one of 'single', 'center', 'simultaneous', 'sequential' or "
            "a number)."
        ),
    )
    easyrpg_using_message: str = Field(
        default="default_message",
        description="Item usage message in battle. EasyRPG Player extension.",
    )
    easyrpg_max_count: int = Field(
        default=-1,
        description="How many the player can carry of this item. EasyRPG Player extension.",
    )


class EnemyAction(DbModel):
    """One entry of a monster's action pattern."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    kind: EnemyActionKind | int = Field(
        default="basic",
        description="Action type (one of 'basic', 'skill', 'transformation' or a number).",
    )
    basic: EnemyActionBasic | int = Field(
        default="dual_attack",
        description=(
            "Basic action (kind='basic'; one of 'attack', 'dual_attack', 'defense', 'observe', "
            "'charge', 'autodestruction', 'escape', 'nothing' or a number)."
        ),
    )
    skill_id: int = Field(default=1, description="Skill (kind='skill'; skill id).")
    enemy_id: int = Field(
        default=1,
        description="Monster to transform into (kind='transformation'; monster id).",
    )
    condition_type: EnemyActionConditionType | int = Field(
        default="always",
        description=(
            "Condition (one of 'always', 'switch', 'turn', 'actors', 'hp', 'sp', 'party_lvl', "
            "'party_fatigue' or a number)."
        ),
    )
    condition_param1: int = Field(
        default=0,
        description="Condition: first value (switch id, turn, %, level...).",
    )
    condition_param2: int = Field(default=0, description="Condition: second value.")
    switch_id: int = Field(default=1, description="Condition switch (switch id).")
    switch_on: bool = Field(default=False, description="Turn a switch ON after the action.")
    switch_on_id: int = Field(default=1, description="Switch turned ON (switch id).")
    switch_off: bool = Field(default=False, description="Turn a switch OFF after the action.")
    switch_off_id: int = Field(default=1, description="Switch turned OFF (switch id).")
    rating: int = Field(default=50, description="Priority (1-10 in the editor).")


class Enemy(DbModel):
    """A monster (Database > Enemies)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    battler_name: str = Field(default="", description="Monster graphic.")
    battler_hue: int = Field(default=0, description="Hue shift of the graphic.")
    max_hp: int = Field(default=10, description="Max hp.")
    max_sp: int = Field(default=10, description="Max sp.")
    attack: int = Field(default=10, description="Attack.")
    defense: int = Field(default=10, description="Defense.")
    spirit: int = Field(default=10, description="Spirit.")
    agility: int = Field(default=10, description="Agility.")
    transparent: bool = Field(default=False, description="Draw translucent.")
    exp: int = Field(default=0, description="Experience given.")
    gold: int = Field(default=0, description="Gold dropped.")
    drop_id: int = Field(default=0, description="Dropped item (0 = none; item id).")
    drop_prob: int = Field(default=100, description="Drop probability in percent.")
    maniac_unarmed_animation: int = Field(
        default=1,
        description=(
            "Animation for normal enemy attacks (Maniac Patch only; battle animation id). Maniac "
            "Patch extension."
        ),
    )
    critical_hit: bool = Field(default=False, description="Can land critical hits.")
    critical_hit_chance: int = Field(default=30, description="Critical hit probability: 1 in N.")
    miss: bool = Field(default=False, description="Attacks often miss.")
    levitate: bool = Field(default=False, description="Flying (floats up and down).")
    state_ranks: list[int] = Field(
        default_factory=list,
        description="State ranks (rank per state id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    attribute_ranks: list[int] = Field(
        default_factory=list,
        description="Attribute ranks (rank per attribute id, index 0 is id 1: 0=A 1=B 2=C 3=D 4=E).",
    )
    actions: list[EnemyAction] = Field(default_factory=list, description="Action pattern.")
    easyrpg_enemyai: int = Field(
        default=-1,
        description=(
            "Default AI behavior of the enemy with 0=RPG_RT 1=RPG_RT+. EasyRPG Player extension."
        ),
    )
    easyrpg_prevent_critical: bool = Field(
        default=False,
        description="If the enemy is protected against critical hits. EasyRPG Player extension.",
    )
    easyrpg_raise_evasion: bool = Field(
        default=False,
        description="If the enemy has an increased evasion rate. EasyRPG Player extension.",
    )
    easyrpg_immune_to_attribute_downshifts: bool = Field(
        default=False,
        description="If the enemy is immune to attribute downshifts. EasyRPG Player extension.",
    )
    easyrpg_ignore_evasion: bool = Field(
        default=False,
        description=(
            "If the enemies unarmed physical attacks ignore evasion. EasyRPG Player extension."
        ),
    )
    easyrpg_hit: int = Field(
        default=-1,
        description="Hit rate of the enemy on normal attacks. EasyRPG Player extension.",
    )
    easyrpg_state_set: list[bool] = Field(
        default_factory=list,
        description=(
            "States inflicted by normal attacks of the enemy (one flag per state id, index 0 is "
            "id 1). EasyRPG Player extension."
        ),
    )
    easyrpg_state_chance: int = Field(
        default=0,
        description=(
            "State infliction probability by normal attacks of the enemy. EasyRPG Player "
            "extension."
        ),
    )
    easyrpg_attribute_set: list[bool] = Field(
        default_factory=list,
        description=(
            "Attributes used by normal attacks of the enemy (one flag per attribute id, index 0 "
            "is id 1). EasyRPG Player extension."
        ),
    )
    easyrpg_super_guard: bool = Field(
        default=False,
        description=(
            "If the enemies defend action quarters instead of halves HP damage. EasyRPG Player "
            "extension."
        ),
    )
    easyrpg_attack_all: bool = Field(
        default=False,
        description=(
            "If the enemies unarmed physical targets the entire player party. EasyRPG Player "
            "extension."
        ),
    )


class TroopMember(DbModel):
    """A monster placed in a troop."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    enemy_id: int = Field(default=1, description="Monster (monster id).")
    x: int = Field(default=0, description="Screen position X.")
    y: int = Field(default=0, description="Screen position Y.")
    invisible: bool = Field(default=False, description="Hidden until shown by an event.")


class Troop(DbModel):
    """A monster party (Database > Troops).

    The troop's battle events (pages) are in database/troop_events.py."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    members: list[TroopMember] = Field(default_factory=list, description="Monsters of the troop.")
    auto_alignment: bool = Field(
        default=False,
        description="Align the monsters automatically. RPG Maker 2003 only.",
    )
    terrain_set: list[bool] = Field(
        default_factory=list,
        description=(
            "Terrains where the troop can be encountered (one flag per terrain id, index 0 is id "
            "1)."
        ),
    )
    appear_randomly: bool = Field(
        default=False,
        description="Random encounter only on the selected terrains. RPG Maker 2003 only.",
    )


class State(DbModel):
    """A condition such as poison or death (Database > States)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    type: StatePersistence | int = Field(
        default="ends",
        description="Whether the state ends after battle (one of 'ends', 'persists' or a number).",
    )
    color: int = Field(default=6, description="Color of the state name.")
    priority: int = Field(default=50, description="Display priority.")
    restriction: StateRestriction | int = Field(
        default="normal",
        description=(
            "Action restriction (one of 'normal', 'do_nothing', 'attack_enemy', 'attack_ally' or "
            "a number)."
        ),
    )
    a_rate: int = Field(default=100, description="Infliction rate for rank A in percent.")
    b_rate: int = Field(default=80, description="Infliction rate for rank B in percent.")
    c_rate: int = Field(default=60, description="Infliction rate for rank C in percent.")
    d_rate: int = Field(default=30, description="Infliction rate for rank D in percent.")
    e_rate: int = Field(default=0, description="Infliction rate for rank E in percent.")
    hold_turn: int = Field(default=0, description="Minimum duration in turns.")
    auto_release_prob: int = Field(
        default=0,
        description="Recovery probability per turn after hold_turn.",
    )
    release_by_damage: int = Field(default=0, description="Recovery probability when damaged.")
    affect_type: StateAffectType | int = Field(
        default="half",
        description=(
            "How the stat changes apply (one of 'half', 'double', 'nothing' or a number). RPG "
            "Maker 2003 only."
        ),
    )
    affect_attack: bool = Field(default=False, description="Changes attack.")
    affect_defense: bool = Field(default=False, description="Changes defense.")
    affect_spirit: bool = Field(default=False, description="Changes spirit.")
    affect_agility: bool = Field(default=False, description="Changes agility.")
    reduce_hit_ratio: int = Field(default=100, description="Hit ratio in percent.")
    avoid_attacks: bool = Field(
        default=False,
        description="Evade all physical attacks. RPG Maker 2003 only.",
    )
    reflect_magic: bool = Field(default=False, description="Reflect magic. RPG Maker 2003 only.")
    cursed: bool = Field(
        default=False,
        description="Equipment cannot be changed. RPG Maker 2003 only.",
    )
    battler_animation_id: int = Field(
        default=100,
        description="Battler animation pose (100 = none; battle animation id). RPG Maker 2003 only.",
    )
    restrict_skill: bool = Field(default=False, description="Blocks physical skills.")
    restrict_skill_level: int = Field(
        default=0,
        description="Physical skills blocked from this attack influence.",
    )
    restrict_magic: bool = Field(default=False, description="Blocks magic skills.")
    restrict_magic_level: int = Field(
        default=0,
        description="Magic skills blocked from this spirit influence.",
    )
    hp_change_type: StateChangeType | int = Field(
        default="lose",
        description="HP change direction (one of 'lose', 'gain', 'nothing' or a number).",
    )
    sp_change_type: StateChangeType | int = Field(
        default="lose",
        description="SP change direction (one of 'lose', 'gain', 'nothing' or a number).",
    )
    message_actor: str = Field(default="", description="Message when an actor is affected.")
    message_enemy: str = Field(default="", description="Message when a monster is affected.")
    message_already: str = Field(default="", description="Message when already affected.")
    message_affected: str = Field(default="", description="Message each turn.")
    message_recovery: str = Field(default="", description="Message on recovery.")
    hp_change_max: int = Field(default=0, description="HP change per turn in percent of max HP.")
    hp_change_val: int = Field(default=0, description="HP change per turn.")
    hp_change_map_steps: int = Field(default=0, description="HP change on the map: every N steps.")
    hp_change_map_val: int = Field(default=0, description="HP change on the map.")
    sp_change_max: int = Field(default=0, description="SP change per turn in percent of max SP.")
    sp_change_val: int = Field(default=0, description="SP change per turn.")
    sp_change_map_steps: int = Field(default=0, description="SP change on the map: every N steps.")
    sp_change_map_val: int = Field(default=0, description="SP change on the map.")
    easyrpg_immune_states: list[bool] = Field(
        default_factory=list,
        description=(
            "States cleared on infliction by this state (one flag per state id, index 0 is id 1). "
            "EasyRPG Player extension."
        ),
    )


class Attribute(DbModel):
    """An attribute / element (Database > Attributes)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    type: AttributeType | int = Field(
        default="physical",
        description="Physical or magical (one of 'physical', 'magical' or a number).",
    )
    a_rate: int = Field(default=300, description="Damage rate for rank A in percent.")
    b_rate: int = Field(default=200, description="Damage rate for rank B in percent.")
    c_rate: int = Field(default=100, description="Damage rate for rank C in percent.")
    d_rate: int = Field(default=50, description="Damage rate for rank D in percent.")
    e_rate: int = Field(default=0, description="Damage rate for rank E in percent.")


class Terrain(DbModel):
    """A terrain type (Database > Terrain)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name.")
    damage: int = Field(default=0, description="Damage per step.")
    encounter_rate: int = Field(default=100, description="Encounter rate multiplier in percent.")
    background_name: str = Field(default="", description="Battle background.")
    boat_pass: bool = Field(default=False, description="Small boat can pass.")
    ship_pass: bool = Field(default=False, description="Ship can pass.")
    airship_pass: bool = Field(default=True, description="Airship can pass.")
    airship_land: bool = Field(default=True, description="Airship can land.")
    bush_depth: TerrainBushDepth | int = Field(
        default="normal",
        description=(
            "How much of a character is hidden (one of 'normal', 'third', 'half', 'full' or a "
            "number)."
        ),
    )
    footstep: Sound = Field(
        default_factory=Sound,
        description="Footstep sound. RPG Maker 2003 only.",
    )
    on_damage_se: bool = Field(
        default=False,
        description="Play the footstep sound only on damage. RPG Maker 2003 only.",
    )
    background_type: TerrainBGAssociation | int = Field(
        default="background",
        description=(
            "Battle background mode (one of 'background', 'frame' or a number). RPG Maker 2003 "
            "only."
        ),
    )
    background_a_name: str = Field(
        default="",
        description="Background a name. RPG Maker 2003 only.",
    )
    background_a_scrollh: bool = Field(
        default=False,
        description="Background a scrollh. RPG Maker 2003 only.",
    )
    background_a_scrollv: bool = Field(
        default=False,
        description="Background a scrollv. RPG Maker 2003 only.",
    )
    background_a_scrollh_speed: int = Field(
        default=0,
        description="Background a scrollh speed. RPG Maker 2003 only.",
    )
    background_a_scrollv_speed: int = Field(
        default=0,
        description="Background a scrollv speed. RPG Maker 2003 only.",
    )
    background_b: bool = Field(default=False, description="Background b. RPG Maker 2003 only.")
    background_b_name: str = Field(
        default="",
        description="Background b name. RPG Maker 2003 only.",
    )
    background_b_scrollh: bool = Field(
        default=False,
        description="Background b scrollh. RPG Maker 2003 only.",
    )
    background_b_scrollv: bool = Field(
        default=False,
        description="Background b scrollv. RPG Maker 2003 only.",
    )
    background_b_scrollh_speed: int = Field(
        default=0,
        description="Background b scrollh speed. RPG Maker 2003 only.",
    )
    background_b_scrollv_speed: int = Field(
        default=0,
        description="Background b scrollv speed. RPG Maker 2003 only.",
    )
    special_flags: TerrainFlags = Field(
        default_factory=TerrainFlags,
        description="Enabled special battle situations. RPG Maker 2003 only.",
    )
    special_back_party: int = Field(
        default=15,
        description="Back attack probability (party) in percent. RPG Maker 2003 only.",
    )
    special_back_enemies: int = Field(
        default=10,
        description="Back attack probability (enemies) in percent. RPG Maker 2003 only.",
    )
    special_lateral_party: int = Field(
        default=10,
        description="Pincer attack probability (party) in percent. RPG Maker 2003 only.",
    )
    special_lateral_enemies: int = Field(
        default=5,
        description="Pincer attack probability (enemies) in percent. RPG Maker 2003 only.",
    )
    grid_location: int = Field(default=0, description="Battle grid location. RPG Maker 2003 only.")
    grid_top_y: int = Field(default=120, description="Battle grid top Y. RPG Maker 2003 only.")
    grid_elongation: int = Field(
        default=392,
        description="Battle grid elongation. RPG Maker 2003 only.",
    )
    grid_inclination: int = Field(
        default=16000,
        description="Battle grid inclination. RPG Maker 2003 only.",
    )
    easyrpg_damage_in_percent: bool = Field(
        default=False,
        description="If the terrain damage is a percentage. EasyRPG Player extension.",
    )
    easyrpg_damage_can_kill: bool = Field(
        default=False,
        description="If the terrain damage can kill the actors. EasyRPG Player extension.",
    )


class BattlerAnimationPose(DbModel):
    """One pose of a battler animation."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    name: str = Field(default="", description="Name. RPG Maker 2003 only.")
    battler_name: str = Field(default="", description="Battle CharSet file. RPG Maker 2003 only.")
    battler_index: int = Field(default=0, description="Index inside the file. RPG Maker 2003 only.")
    animation_type: BattlerAnimationPoseAnimType | int = Field(
        default="character",
        description=(
            "Battle CharSet or battle animation (one of 'character', 'battle' or a number). RPG "
            "Maker 2003 only."
        ),
    )
    battle_animation_id: int = Field(
        default=1,
        description=(
            "Battle animation (animation_type='battle'; battle animation id). RPG Maker 2003 "
            "only."
        ),
    )


class BattlerAnimationWeapon(DbModel):
    """One weapon graphic of a battler animation."""

    id: int | None = Field(
        default=None,
        description="Element id; leave it out to use the position in the list (1-based).",
    )
    name: str = Field(default="", description="Name. RPG Maker 2003 only.")
    weapon_name: str = Field(default="", description="Weapon graphic file. RPG Maker 2003 only.")
    weapon_index: int = Field(default=0, description="Index inside the file. RPG Maker 2003 only.")


class BattlerAnimation(DbModel):
    """A battle character set: poses and weapons of a 2003 battler (Database > Battle Animation 2)."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name. RPG Maker 2003 only.")
    speed: BattlerAnimationSpeed | int = Field(
        default="slow",
        description=(
            "Animation speed (one of 'slow', 'medium', 'fast' or a number). RPG Maker 2003 only."
        ),
    )
    poses: list[BattlerAnimationPose] = Field(
        default_factory=list,
        description=(
            "Poses (Idle, AttackRight, AttackLeft, Skill, Dead, Damage, Dazed, Defend, WalkLeft, "
            "WalkRight, Victory, Item, ...). RPG Maker 2003 only."
        ),
    )
    weapons: list[BattlerAnimationWeapon] = Field(
        default_factory=list,
        description="Weapon graphics. RPG Maker 2003 only.",
    )


class Switch(DbModel):
    """A switch name."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name shown in the editor.")


class Variable(DbModel):
    """A variable name."""

    id: int | None = Field(
        default=None,
        description=(
            "Database id: entry N is the N-th slot of the table (RPG_RT looks entries up by "
            "position)."
        ),
    )
    name: str = Field(default="", description="Name shown in the editor.")
