"""The event script language of rpgsync: typed and documented vocabulary.

Every script starts with ``from rpgsync.dsl import *``.  rpgsync *parses*
scripts and never runs them, so nothing here does anything at runtime: the
classes and signatures exist so that editors autocomplete, show these docs
on hover, and type checkers (ty, pyright) flag wrong values while you type.

Example::

    @event(9, "Guard", x=10, y=5)
    def guard():
        @page(sprite=("Actor1", 3), layer="same")
        def page_1():
            text("Halt!")
            if variables[1] >= variables[2]:
                party.gold -= 100
            match show_choices("Pay", "Leave"):
                case "Pay":
                    switches[4] = True
                case "Leave":
                    this.move(move_away_from_player, frequency=6)
                    return

        @page(when=switches[4], sprite=("Actor1", 3), layer="same")
        def page_2():
            text("Welcome back.")

Conventions:

* Ranges use Python slices: ``variables[1:11]`` is variables 1 to 10.
* Most numbers can also be given as ``variables[id]`` (the value is read
  when the command runs).
* ``extra=(...)`` keeps raw parameters added by newer editor versions or
  patches; ``some_field=None`` marks a parameter that older editors did not
  write.  Both are generated by rpgsync to keep data byte-identical; you
  rarely need them yourself.
* Python ``#`` comments on their own line are stored as RPG Maker comments.
"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager, nullcontext
from typing import Literal, TypeVar, overload

_F = TypeVar("_F", bound=Callable[..., object])

# ==========================================================================
# Accepted values
# ==========================================================================

Direction = Literal["up", "right", "down", "left"]
"""A facing direction."""
TeleportDirection = Literal["retain", "up", "right", "down", "left"]
"""Facing after a teleport / move: ``"retain"`` keeps the current one."""
Trigger = Literal["action", "touch", "collision", "autorun", "parallel"]
"""How an event page starts:

* ``"action"``: the player presses the action key next to it (or on it).
* ``"touch"``: the player walks into it.
* ``"collision"``: the player walks into it, or it walks into the player.
* ``"autorun"``: starts by itself and blocks the player until it ends.
* ``"parallel"``: runs repeatedly in the background while the player moves.
"""
Layer = Literal["below", "same", "above"]
"""Drawing/collision layer of an event: below the hero (walkable), same as
the hero (blocks, can be talked to) or above the hero."""
MoveType = Literal["stationary", "random", "vertical", "horizontal", "toward_player", "away_from_player", "custom"]
"""Automatic movement of an event page (``"custom"`` uses ``route=``)."""
Pattern = Literal["left", "middle", "right", "middle2"]
"""Animation frame of the sprite shown when the event stands still."""
AnimationType = Literal[
    "non_continuous",
    "continuous",
    "fixed_non_continuous",
    "fixed_continuous",
    "fixed_graphic",
    "spin",
    "step_frame_fix",
]
"""How the sprite animates: walking only when moving (non_continuous),
always (continuous), with a fixed direction, frozen (fixed_graphic) or
spinning."""
Speed = Literal[1, 2, 3, 4, 5, 6]
"""Movement speed: 1 = 1/8, 2 = 1/4, 3 = 1/2, 4 = normal, 5 = x2, 6 = x4."""
Frequency = Literal[1, 2, 3, 4, 5, 6, 7, 8]
"""How often an event acts: 1 = rarely ... 8 = continuously.  It affects
moving, turning and waiting, not graphic changes."""
SpriteIndex = Literal[0, 1, 2, 3, 4, 5, 6, 7]
"""Which of the 8 characters of a CharSet image (288x256), counted left to
right, top to bottom, from 0 at the top left::

    +---+---+---+---+
    | 0 | 1 | 2 | 3 |
    +---+---+---+---+
    | 4 | 5 | 6 | 7 |
    +---+---+---+---+

Each character block holds 3 walking frames across and 4 directions down
(up, right, down, left); the page's ``direction`` and ``pattern`` pick the
pose inside it."""
FaceIndex = Literal[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
"""Which of the 16 faces (48x48) of a FaceSet image, counted left to right,
top to bottom: 0-3 on the first row ... 12-15 on the last."""
CommonEventTrigger = Literal["call", "autorun", "parallel"]
"""When a common event runs: only when called, automatically (blocking), or
in parallel; autorun/parallel common events need their condition switch ON."""
MessagePosition = Literal["top", "middle", "bottom"]
Vehicle = Literal["boat", "ship", "airship"]
CancelOption = Literal[1, 2, 3, 4]
Digits = Literal[1, 2, 3, 4, 5, 6, 7]
Transition = Literal[
    "default",
    "fade",
    "random_blocks",
    "random_blocks_down",
    "random_blocks_up",
    "blinds",
    "vertical_stripes",
    "horizontal_stripes",
    "border_to_center",
    "center_to_border",
    "scroll_up",
    "scroll_down",
    "scroll_left",
    "scroll_right",
    "vertical_split",
    "horizontal_split",
    "cross_split",
    "zoom",
    "mosaic",
    "ripple",
    "instant",
    "none",
]
"""Screen transition; ``"default"`` uses the one set in the database
(System tab) or with set_transition()."""
TransitionKind = Literal[
    "teleport_erase", "teleport_show", "battle_start_erase", "battle_start_show", "battle_end_erase", "battle_end_show"
]
WeatherKind = Literal["none", "rain", "snow", "fog", "sandstorm"]
Strength = Literal["weak", "medium", "strong"]
FlashMode = Literal["once", "begin", "end"]
"""``"once"`` flashes/shakes once; ``"begin"`` repeats until ``"end"`` (2003)."""
PictureEffect = Literal["none", "rotation", "wave"]
Stat = Literal["max_hp", "max_sp", "attack", "defense", "spirit", "agility"]
EquipSlot = Literal["weapon", "shield", "armor", "helmet", "accessory", "all"]
BgmContext = Literal["battle", "victory", "inn", "boat", "ship", "airship", "game_over"]
SeContext = Literal[
    "cursor",
    "decision",
    "cancel",
    "buzzer",
    "battle_start",
    "escape",
    "enemy_attack",
    "enemy_damaged",
    "ally_damaged",
    "evade",
    "enemy_dies",
    "item",
]
SkillMode = Literal["keep", "replace", "add"]
StatMode = Literal["keep", "halve", "level1", "current_level"]

# Command names accepted by cmd(...), from liblcf.
CommandName = Literal[
    "BreakLoop",
    "CallCommonEvent",
    "CallEvent",
    "ChangeActorFace",
    "ChangeBattleBG",
    "ChangeBattleCommands",
    "ChangeClass",
    "ChangeCondition",
    "ChangeEncounterSteps",
    "ChangeEquipment",
    "ChangeEscapeAccess",
    "ChangeEventLocation",
    "ChangeExp",
    "ChangeFaceGraphic",
    "ChangeGold",
    "ChangeHP",
    "ChangeHeroName",
    "ChangeHeroTitle",
    "ChangeItems",
    "ChangeLevel",
    "ChangeMainMenuAccess",
    "ChangeMapTileset",
    "ChangeMonsterCondition",
    "ChangeMonsterHP",
    "ChangeMonsterMP",
    "ChangePBG",
    "ChangeParameters",
    "ChangePartyMembers",
    "ChangeSP",
    "ChangeSaveAccess",
    "ChangeScreenTransitions",
    "ChangeSkills",
    "ChangeSpriteAssociation",
    "ChangeSystemBGM",
    "ChangeSystemGraphics",
    "ChangeSystemSFX",
    "ChangeTeleportAccess",
    "ChangeVehicleGraphic",
    "Comment",
    "Comment_2",
    "ConditionalBranch",
    "ConditionalBranch_B",
    "ControlSwitches",
    "ControlVars",
    "DefeatHandler",
    "END",
    "ElseBranch",
    "ElseBranch_B",
    "EnableCombo",
    "EndBattle",
    "EndBranch",
    "EndBranch_B",
    "EndEventProcessing",
    "EndInn",
    "EndLoop",
    "EndShop",
    "EnemyEncounter",
    "EnterExitVehicle",
    "EnterHeroName",
    "EraseEvent",
    "ErasePicture",
    "EraseScreen",
    "EscapeHandler",
    "EscapeTarget",
    "ExitGame",
    "FadeOutBGM",
    "FlashScreen",
    "FlashSprite",
    "ForceFlee",
    "FullHeal",
    "GameOver",
    "HaltAllMovement",
    "InputNumber",
    "JumpToLabel",
    "KeyInputProc",
    "Label",
    "Loop",
    "MemorizeBGM",
    "MemorizeLocation",
    "MessageOptions",
    "MoveEvent",
    "MovePicture",
    "NoStay",
    "NoTransaction",
    "OpenLoadMenu",
    "OpenMainMenu",
    "OpenSaveMenu",
    "OpenShop",
    "OpenVideoOptions",
    "PanScreen",
    "PlayBGM",
    "PlayMemorizedBGM",
    "PlayMovie",
    "PlaySound",
    "PlayerVisibility",
    "ProceedWithMovement",
    "RecallToLocation",
    "ReturntoTitleScreen",
    "SetVehicleLocation",
    "ShakeScreen",
    "ShowBattleAnimation",
    "ShowBattleAnimation_B",
    "ShowChoice",
    "ShowChoiceEnd",
    "ShowChoiceOption",
    "ShowHiddenMonster",
    "ShowInn",
    "ShowMessage",
    "ShowMessage_2",
    "ShowPicture",
    "ShowScreen",
    "SimulatedAttack",
    "Stay",
    "StoreEventID",
    "StoreTerrainID",
    "TeleportTargets",
    "Teleport",
    "TerminateBattle",
    "TileSubstitution",
    "TimerOperation",
    "ToggleAtbMode",
    "ToggleFullscreen",
    "TradeEventLocations",
    "Transaction",
    "VictoryHandler",
    "Wait",
    "WeatherEffects",
]

Extra = tuple[int, ...]
"""Raw trailing parameters kept for lossless round trips (newer editors, patches)."""


# ==========================================================================
# Values and conditions
# ==========================================================================


class Condition:
    """Something an ``if`` or ``@page(when=...)`` can test."""

    def __bool__(self) -> bool: ...


class Value:
    """A number read from the game when the command runs (a variable, a
    stat, the gold...).  Compare it to get a condition:
    ``variables[1] >= 10``, ``variables[1] == variables[2]``."""

    def __eq__(self, other: object) -> Condition: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Condition: ...  # type: ignore[override]
    def __lt__(self, other: int | Value) -> Condition: ...
    def __le__(self, other: int | Value) -> Condition: ...
    def __gt__(self, other: int | Value) -> Condition: ...
    def __ge__(self, other: int | Value) -> Condition: ...
    def __neg__(self) -> Value: ...
    def __pos__(self) -> Value: ...


Number = int | Value
"""A number, or a value read from the game such as ``variables[3]``."""


class Counter(Value):
    """A value changed with ``+=`` / ``-=`` (gold, item counts)."""

    def __iadd__(self, amount: Number) -> Counter: ...
    def __isub__(self, amount: Number) -> Counter: ...


class Variable(Value):
    """One game variable, ``variables[id]``.

    Assign with ``=``, change with ``+= -= *= //= %=`` (``%`` is the
    remainder: 1953 % 100 = 53).  Values range from -9999999 to 9999999 in
    RPG Maker 2003 (-999999 to 999999 in 2000)."""

    def __iadd__(self, value: Number) -> Variable: ...
    def __isub__(self, value: Number) -> Variable: ...
    def __imul__(self, value: Number) -> Variable: ...
    def __ifloordiv__(self, value: Number) -> Variable: ...
    def __imod__(self, value: Number) -> Variable: ...


class VariableRange:
    """``variables[first:last+1]``: the same operation on every variable of the range."""

    def __iadd__(self, value: Number) -> VariableRange: ...
    def __isub__(self, value: Number) -> VariableRange: ...
    def __imul__(self, value: Number) -> VariableRange: ...
    def __ifloordiv__(self, value: Number) -> VariableRange: ...
    def __imod__(self, value: Number) -> VariableRange: ...


class Variables:
    """All game variables: ``variables[5]``, ``variables[1:11]`` (1 to 10),
    ``variables[variables[3]]`` (the variable whose id is stored in variable 3)."""

    @overload
    def __getitem__(self, key: int | Variable) -> Variable: ...
    @overload
    def __getitem__(self, key: slice) -> VariableRange: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key: int | Variable | slice, value: Number | VariableRange | Variable) -> None: ...


class Switch(Condition):
    """One game switch, ``switches[id]`` (ON/OFF).  Set it with ``= True`` /
    ``= False``, test it with ``if switches[id]:`` or ``if not switches[id]:``."""

    def toggle(self) -> None:
        """Flip the switch: ON becomes OFF and OFF becomes ON."""


class SwitchRange:
    """``switches[first:last+1]``: several switches at once."""

    def toggle(self) -> None:
        """Flip every switch of the range."""


class Switches:
    """All game switches: ``switches[5]``, ``switches[1:11]`` (1 to 10),
    ``switches[variables[3]]`` (the switch whose id is in variable 3)."""

    @overload
    def __getitem__(self, key: int | Variable) -> Switch: ...
    @overload
    def __getitem__(self, key: slice) -> SwitchRange: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key: int | Variable | slice, value: bool) -> None: ...


class Item:
    """``items[id]``: an item of the database.  ``items[3].count += 2`` gives
    two, ``if items[3] in party:`` tests possession.  The inventory is sorted
    by item id."""

    count: Counter
    """How many the party holds."""
    equipped: Value
    """How many are currently equipped by party members."""


class Items:
    def __getitem__(self, key: int | Variable) -> Item: ...


class Actor:
    """``actors[id]``: a hero of the database (in the party or not)."""

    name: str
    """The hero's name; assign to rename (``actors[1].name = "Alex"``).
    Message codes work in it, but not \\v[] (variable display)."""
    title: str
    """The hero's title (grade); assign to change it."""
    level: Value
    exp: Value
    hp: Value
    sp: Value
    max_hp: Value
    max_sp: Value
    attack: Value
    defense: Value
    spirit: Value
    agility: Value
    weapon: Value
    """Id of the equipped weapon (0 = none)."""
    shield: Value
    armor: Value
    helmet: Value
    accessory: Value
    can_act: Condition
    """In ``battle_condition(...)``: the hero can act this turn."""

    def knows(self, skill: int) -> Condition:
        """Condition: the hero has learned this skill."""

    def has_equipped(self, item: int) -> Condition:
        """Condition: the hero has this item equipped."""

    def has_state(self, state: int) -> Condition:
        """Condition: the hero has this state (poison, sleep...)."""

    def uses_command(self, command: int) -> Condition:
        """In ``battle_condition(...)``: the hero uses this battle command (2003)."""

    def set_sprite(self, charset: str, index: int | None = None, transparent: bool | None = None) -> None:
        """Change the hero's walking sprite.

        Args:
            charset: CharSet image name.
            index: character in the CharSet image (0-7).
            transparent: draw the hero semi-transparent.
        """

    def set_face(self, faceset: str, index: int | None = None) -> None:
        """Change the hero's face (used by messages and menus).

        Args:
            faceset: FaceSet image name.
            index: face in the FaceSet image (0-15).
        """


class Actors:
    def __getitem__(self, key: int | Variable) -> Actor: ...


class MoveStep:
    """One step of a move route (move_up, face_player, switch_on(3), ...).
    ``move_up * 3`` repeats a step."""

    def __mul__(self, count: int) -> MoveStep: ...


# ==========================================================================
# Move route steps
# ==========================================================================

move_up = MoveStep()
"""Move one tile up."""
move_right = MoveStep()
"""Move one tile right."""
move_down = MoveStep()
"""Move one tile down."""
move_left = MoveStep()
"""Move one tile left."""
move_up_right = MoveStep()
"""Move one tile diagonally up-right."""
move_down_right = MoveStep()
"""Move one tile diagonally down-right."""
move_down_left = MoveStep()
"""Move one tile diagonally down-left."""
move_up_left = MoveStep()
"""Move one tile diagonally up-left."""
move_random = MoveStep()
"""Move one tile in a random direction."""
move_toward_player = MoveStep()
"""Move one tile toward the player."""
move_away_from_player = MoveStep()
"""Move one tile away from the player."""
move_forward = MoveStep()
"""Move one tile in the facing direction."""
face_up = MoveStep()
"""Turn to face up."""
face_right = MoveStep()
"""Turn to face right."""
face_down = MoveStep()
"""Turn to face down."""
face_left = MoveStep()
"""Turn to face left."""
turn_right = MoveStep()
"""Turn 90 degrees clockwise."""
turn_left = MoveStep()
"""Turn 90 degrees counterclockwise."""
turn_around = MoveStep()
"""Turn 180 degrees."""
turn_random = MoveStep()
"""Turn 90 degrees left or right at random."""
face_random = MoveStep()
"""Face a random direction."""
face_player = MoveStep()
"""Face the player."""
face_away_from_player = MoveStep()
"""Turn the back to the player."""
pause = MoveStep()
"""Wait one movement step."""
jump_start = MoveStep()
"""Start a jump: the following movement steps set where it lands."""
jump_end = MoveStep()
"""End a jump started with jump_start: land where the steps in between lead."""
lock_facing = MoveStep()
"""Keep the current facing direction while moving."""
unlock_facing = MoveStep()
"""Face the direction of movement again."""
speed_up = MoveStep()
"""Move one speed faster (speeds go from 1 to 6)."""
speed_down = MoveStep()
"""Move one speed slower."""
frequency_up = MoveStep()
"""Act more often (frequency goes from 1 to 8)."""
frequency_down = MoveStep()
"""Act less often."""
phasing_on = MoveStep()
"""Walk through everything."""
phasing_off = MoveStep()
"""Stop walking through everything."""
stop_animation = MoveStep()
"""Stop the walking animation."""
start_animation = MoveStep()
"""Animate the walking again."""
transparency_up = MoveStep()
"""One step more transparent (0 = opaque, 7 = most)."""
transparency_down = MoveStep()
"""One step less transparent."""


def switch_on(switch: int | Switch) -> MoveStep:
    """Move step: turn a switch ON: ``switch_on(switches.door_open)``."""
    return MoveStep()


def switch_off(switch: int | Switch) -> MoveStep:
    """Move step: turn a switch OFF: ``switch_off(switches.door_open)``."""
    return MoveStep()


def change_graphic(charset: str, index: SpriteIndex) -> MoveStep:
    """Move step: change the character's graphic to character ``index`` (0-7,
    see SpriteIndex) of the CharSet image ``charset`` (file name without
    extension)."""
    return MoveStep()


# play_se(name, volume, tempo, balance) is a move step too (see Audio).


def move(code: int) -> MoveStep:
    """Move step by its raw code (for codes rpgsync has no name for)."""
    return MoveStep()


class Character:
    """A character on the map: ``this``, ``player``, ``events[id]``, vehicles."""

    map_id: Value
    x: Value
    y: Value
    direction: Value
    screen_x: Value
    screen_y: Value
    facing: Direction
    """Test with ``this.facing == "up"``."""

    def move(self, *steps: MoveStep, frequency: Frequency = 6, repeat: bool = False, skippable: bool = False) -> None:
        """Move Event: give the character a route to follow.

        Between ``jump_start`` and ``jump_end`` only movement steps count.
        Speed can only change relative to the current one (speed_up /
        speed_down).

        Args:
            steps: the route, e.g. ``move_up * 3, face_left``.
            frequency: 1 (slow) to 8 (continuous); affects moving, turning and waiting.
            repeat: loop the route forever.
            skippable: skip steps that cannot be done (blocked) instead of waiting.
        """

    def set_location(self, x: Number, y: Number, direction: TeleportDirection = "retain") -> None:
        """Set Event Location: move this event instantly.  x and y are both
        numbers or both variables[id]."""

    def show_animation(self, animation: int, wait: bool = False, whole_map: bool = False) -> None:
        """Show Battle Animation on this character (also works outside battle).

        Args:
            animation: animation id of the database.
            wait: wait until the animation ends.
            whole_map: play it over the whole screen instead of the character.
        """

    def call(self, page: Number) -> None:
        """Call Event: run one page of this map event and wait for it."""

    def flash(
        self,
        red: int | None = None,
        green: int | None = None,
        blue: int | None = None,
        strength: int | None = None,
        duration: float | None = None,
        wait: bool | None = None,
        extra: Extra = (),
    ) -> None:
        """Flash the character with a colour.

        Args:
            red, green, blue: colour, 0-31 each (default 31).
            strength: 0-31 (default 31).
            duration: seconds, in steps of 0.1 (default 0.5).
            wait: wait until the flash ends.
        """


class ThisEvent(Character):
    def erase(self) -> None:
        """Erase Event: remove this event until the player re-enters the map."""


class PlayerCharacter(Character):
    vehicle: Vehicle | None
    """Test with ``player.vehicle == "boat"``."""
    visible: bool
    """Assign to hide or show the hero (``player.visible = False``)."""


class VehicleCharacter(Character):
    def set_sprite(self, charset: str, index: int | None = None) -> None:
        """Change the vehicle's graphic (CharSet name and character 0-7)."""


class Events:
    def __getitem__(self, key: int | Variable) -> Character: ...


class CommonEvent:
    def __call__(self) -> None:
        """Call this common event and wait for it to end."""


class CommonEvents:
    def __getitem__(self, key: int) -> CommonEvent: ...


class CommonEventTable(CommonEvents):
    """The common events of database/common_events.py: its @common_event
    functions, called as ``common_events.name()`` (``common_events[10]()``
    works too).  The nested ``class Config:`` holds ``size``, the number of
    slots the editor shows."""


class CommonEventFunction:
    """A function decorated with @common_event: ``common_events.name()`` calls it."""

    @overload
    def __get__(self, obj: None, owner: type, /) -> CommonEventFunction: ...
    @overload
    def __get__(self, obj: object, owner: type, /) -> CommonEvent: ...
    def __get__(self, obj: object, owner: type, /) -> CommonEventFunction | CommonEvent:
        return CommonEvent()


class Percent(Value):
    """``percent(n)``: n% of the target's HP."""


class Enemy:
    """``enemies[i]``: an enemy of the current battle (troop member)."""

    hp: Value
    sp: Value
    max_hp: Value
    max_sp: Value
    attack: Value
    defense: Value
    spirit: Value
    agility: Value
    can_act: Condition
    """In ``battle_condition(...)``: the enemy can act."""
    targeted: Condition
    """In ``battle_condition(...)``: the enemy is the current target."""

    def change_hp(self, amount: Number | Percent, lethal: bool | None = None, extra: Extra = ()) -> None:
        """Change the enemy's HP (negative = damage); ``percent(n)`` changes
        by n% of its HP.  It cannot die unless ``lethal=True``."""

    def change_sp(self, amount: Number, extra: Extra = ()) -> None:
        """Change the enemy's SP (negative = lose)."""

    def add_state(self, state: int) -> None:
        """Inflict a state on the enemy."""

    def remove_state(self, state: int) -> None:
        """Cure a state of the enemy."""

    def show(self) -> None:
        """Make a hidden enemy appear."""


class Enemies:
    def __getitem__(self, key: int) -> Enemy: ...


class Picture:
    """``pictures[id]``: one of the screen pictures.  Pictures with a higher
    number are drawn on top; coordinates are the picture's centre."""

    def show(
        self,
        name: str,
        *,
        x: Number = 0,
        y: Number = 0,
        scroll_with_map: bool | None = None,
        magnify: int | None = None,
        transparency: int | None = None,
        transparent_color: bool | None = None,
        red: int | None = None,
        green: int | None = None,
        blue: int | None = None,
        saturation: int | None = None,
        effect: PictureEffect | None = None,
        effect_power: int | None = None,
        bottom_transparency: int | None = None,
        extra: Extra = (),
    ) -> None:
        """Show Picture.

        Args:
            name: image of the Picture folder.
            x, y: centre position in pixels; both numbers or both variables[id].
            scroll_with_map: move with the map instead of staying on screen.
            magnify: zoom in percent (100 = normal).  Avoid scrolling the map
                with a picture zoomed below 2%: RPG_RT can crash.
            transparency: 0 (opaque) to 100 (invisible).
            transparent_color: draw the image's transparent colour as transparent.
            red, green, blue, saturation: tint, 0-200 (100 = unchanged).
            effect: none, rotation or wave.
            effect_power: speed of the rotation / strength of the wave.
            bottom_transparency: transparency of the lower half (2003; defaults to transparency).
        """

    def move(
        self,
        *,
        x: Number = 0,
        y: Number = 0,
        magnify: int | None = None,
        transparency: int | None = None,
        red: int | None = None,
        green: int | None = None,
        blue: int | None = None,
        saturation: int | None = None,
        effect: PictureEffect | None = None,
        effect_power: int | None = None,
        duration: float | None = None,
        wait: bool | None = None,
        bottom_transparency: int | None = None,
        p4: int | None = None,
        p7: int | None = None,
        extra: Extra = (),
    ) -> None:
        """Move Picture: change position, zoom, transparency or tint over time.

        Args:
            x, y: new centre position (both numbers or both variables[id]).
            duration: seconds, in steps of 0.1.
            wait: wait until the move ends.
            (other arguments: as in show(); p4/p7 are unused raw parameters)
        """

    def erase(self, extra: Extra = ()) -> None:
        """Erase Picture."""


class Pictures:
    def __getitem__(self, key: int) -> Picture: ...


class Party:
    """The hero party."""

    gold: Counter
    """``party.gold += 100``, ``if party.gold >= 100:``"""
    size: Value
    """Number of heroes in the party."""

    def add(self, actor: Actor) -> None:
        """Add a hero to the party (up to 4)."""

    def remove(self, actor: Actor) -> None:
        """Remove a hero from the party."""

    def __contains__(self, member: Item | Actor) -> bool:
        """``items[3] in party`` (holds the item) / ``actors[2] in party``."""


class Timer:
    """``timer1`` / ``timer2`` (2003): a countdown shown on screen."""

    seconds: Value
    """Seconds left; test with ``timer1.seconds <= 10``."""

    def set(self, seconds: Number, visible: bool | None = None, in_battle: bool | None = None) -> None:
        """Set the timer's start value (it does not start yet)."""

    def start(self, seconds: Number | None = None, visible: bool | None = None, in_battle: bool | None = None) -> None:
        """Start the countdown.

        Args:
            visible: show the timer on screen.
            in_battle: keep counting during battles.
            seconds: raw value stored with the command (unused by RPG Maker).
        """

    def stop(self, seconds: Number | None = None, visible: bool | None = None, in_battle: bool | None = None) -> None:
        """Stop the countdown."""


class GameState:
    """Game-wide statistics and permissions."""

    save_count: Value
    battle_count: Value
    win_count: Value
    defeat_count: Value
    escape_count: Value
    midi_ticks: Value
    """Position in the current MIDI music."""
    allow_teleport: bool
    """Assign to allow/forbid teleport skills."""
    allow_escape: bool
    """Assign to allow/forbid escape skills."""
    allow_save: bool
    """Assign to allow/forbid saving from the menu."""
    allow_menu: bool
    """Assign to allow/forbid opening the main menu."""


class DynToken:
    """A DynRPG variable/actor token: ``V[12]`` is written ``V12`` in the comment."""


class _DynTokenPrefix:
    def __getitem__(self, number: int) -> DynToken: ...


class DynRPG:
    """DynRPG plugin calls, stored as "@function args" comments:
    ``dyn.change_text("id", r"\\v[1]", 0)``, ``dyn.dynparams_add_param(2, V[152])``."""

    def __getattr__(self, function: str) -> Callable[..., None]: ...


# `variables` and `switches` come from the game's database/variables.py and
# database/switches.py (classes of rpgsync.tables), which name them.
items = Items()
actors = Actors()
events = Events()
"""Events of the current map, by id."""
enemies = Enemies()
pictures = Pictures()
party = Party()
this = ThisEvent()
"""The event running the script."""
player = PlayerCharacter()
"""The hero on the map."""
boat = VehicleCharacter()
ship = VehicleCharacter()
airship = VehicleCharacter()
timer1 = Timer()
timer2 = Timer()
game = GameState()
dyn = DynRPG()
V = VV = VVV = v = vv = vvv = N = NV = NVV = n = nv = nvv = _DynTokenPrefix()
started_by_action_key = Condition()
"""Condition: the event was started with the action key."""
bgm_looped = Condition()
"""Condition: the current music has played through once (MIDI only; also
true right after loading a save)."""


def randint(a: int, b: int) -> Value:
    """A random number from a to b (inclusive), like random.randint."""
    return Value()


def percent(value: int) -> Percent:
    """n% of the target's HP, for enemies[i].change_hp()."""
    return Percent()


def input_number(digits: Digits) -> Value:
    """Input Number: the player types a number.

    ``variables[3] = input_number(digits=4)``

    Args:
        digits: how many digits the player can type (1-6 in 2000, 1-7 in 2003).
    """
    return Value()


def terrain_id(x: Number, y: Number) -> Value:
    """The terrain id of a map tile: ``variables[5] = terrain_id(10, 4)``.
    Empty tiles give the chipset's first terrain (water)."""
    return Value()


def event_id_at(x: Number, y: Number) -> Value:
    """The id of the event on a tile (the highest if several, 0 if none):
    ``variables[5] = event_id_at(this.x, this.y)``."""
    return Value()


def key_input(
    *,
    wait: bool | int = False,
    directions: bool | int = False,
    decision: bool | int = False,
    cancel: bool | int = False,
    numbers: bool | int = False,
    operators: bool | int = False,
    time_variable: Variable | None = None,
    count_time: bool | int = False,
    shift: bool | int = False,
    down: bool | int = False,
    left: bool | int = False,
    right: bool | int = False,
    up: bool | int = False,
    layout: Literal[2000, 2003] | None = None,
) -> Value:
    """Key Input Processing: ``variables[148] = key_input(down=True, up=True, wait=True)``.

    The variable receives the key pressed: 1 down, 2 left, 3 right, 4 up,
    5 decision, 6 cancel, 7 shift, 10-19 numbers 0-9, 20-24 + - * / and .
    (0 when nothing was pressed).

    Args:
        wait: wait until one of the keys is pressed.
        directions: all four arrows at once (older editor versions).
        decision, cancel, shift, down, left, right, up: keys to check.
        numbers, operators: number and operator keys (2003).
        time_variable: store the time taken, in tenths of a second (2003).
        count_time: whether time_variable is used.
        layout: parameter layout of another editor version (set by rpgsync).
    Flags may be integers when the Maniac Patch stores mouse buttons.
    """
    return Value()


def cond(kind: int, a: int, b: int, c: int, d: int) -> Condition:
    """Any other Conditional Branch, by its raw parameters."""
    return Condition()


def battle_condition(condition: Condition | bool) -> Condition:
    """A battle Conditional Branch (troop events): switches, variables,
    ``actors[id].can_act``, ``enemies[i].can_act``, ``enemies[i].targeted``,
    ``actors[id].uses_command(n)``.  Example: ``if battle_condition(enemies[0].targeted):``"""
    return Condition()


# ==========================================================================
# Structure
# ==========================================================================


class Route:
    """A custom move route for page(route=...)."""


def event(id: int | None = None, name: str = "", x: int = 0, y: int = 0) -> Callable[[_F], Character]:
    """A map event.

    Args:
        id: event id; leave it out for a new event: the lowest free id is
            assigned and written back into the script.
        name: name shown in the editor.
        x, y: tile position on the map.
    """
    return lambda fn: fn


def page(
    *,
    when: Condition | bool | None = None,
    sprite: tuple[str, SpriteIndex] | None = None,
    tile: int | None = None,
    direction: Direction = "down",
    pattern: Pattern = "middle",
    translucent: bool = False,
    trigger: Trigger = "action",
    layer: Layer = "below",
    overlap_forbidden: bool = False,
    animation: AnimationType = "non_continuous",
    move_type: MoveType = "stationary",
    frequency: Frequency = 3,
    speed: Speed = 3,
    route: Route | None = None,
    id: int | None = None,
    raw: bool = False,
    switch_a: int | None = None,
    switch_b: int | None = None,
    variable: tuple[int, str, int] | None = None,
    item: int | None = None,
    actor: int | None = None,
    timer: int | None = None,
    timer2: int | None = None,
) -> Callable[[_F], _F]:
    """An event page.  Pages are listed in order; the last page whose
    conditions hold is the active one.

    Args:
        when: conditions joined with ``and``: up to two ``switches[id]``,
            ``variables[id] >= n`` (any comparison in 2003),
            ``items[id] in party``, ``actors[id] in party``,
            ``timer1.seconds <= n``, ``timer2.seconds <= n``.
        sprite: ("CharSet", 0-7), the event's graphic; the index counts the
            8 characters of the image left to right, top to bottom (see
            SpriteIndex).
        tile: a tile of the chipset as graphic, instead of a sprite.
        direction: facing direction of the graphic.
        pattern: animation frame shown when standing still.
        translucent: draw semi-transparent.
        trigger: how the page starts (action, touch, collision, autorun, parallel).
        layer: below, same level as, or above the hero.
        overlap_forbidden: other events cannot walk through it.
        animation: how the sprite animates.
        move_type: automatic movement; "custom" follows ``route``.
        frequency: how often it moves (1-8).
        speed: movement speed (1 = 1/8 ... 4 = normal ... 6 = x4).
        route: route(...) followed when move_type="custom".
        id: page number when pages are not numbered 1, 2, 3...
        raw: the body is raw cmd(..., indent=N) lines (set by rpgsync).
        switch_b: the editor's second switch slot, for pages that leave the
            first one unchecked (``when`` puts a single switch in the first
            slot; both behave the same).
        switch_a, variable, item, actor, timer, timer2: the conditions in
            explicit form (used instead of ``when`` for rare combinations).
    """
    return lambda fn: fn


def common_event(
    id: int | None = None,
    name: str = "",
    trigger: CommonEventTrigger = "call",
    switch: int | None = None,
    raw: bool = False,
) -> Callable[[Callable[[], None]], CommonEventFunction]:
    """A common event of the database.  Leave out the id for a new one.

    Args:
        trigger: call (run with common_events[id]()), autorun or parallel.
        switch: condition switch of an autorun/parallel common event.
        raw: the body is raw cmd(...) lines (set by rpgsync).
    """
    return lambda fn: fn


def route(*steps: MoveStep, repeat: bool = True, skippable: bool = False) -> Route:
    """Custom move route: ``route(move_up * 2, move_down * 2, repeat=True)``."""
    return Route()


# ==========================================================================
# Messages
# ==========================================================================


def text(*lines: str) -> None:
    """Show Message: one argument per line, up to 4 lines per box.

    Message codes: \\c[n] colour (0-19, from the System graphic), \\s[n] text
    speed (1 fastest - 20 slowest), \\v[n] variable value, \\n[n] hero name,
    \\$ gold window, \\. short pause, \\| long pause, \\! wait for a key,
    \\^ close automatically, \\> \\< show instantly.  Use raw strings
    (r"...") so backslashes stay as typed."""


def comment(*lines: str) -> None:
    """An editor comment, kept in the game data.  A full-line ``# text`` in a
    script does the same; DynRPG plugin calls are written ``dyn.function(...)``."""


def face(faceset: str | None, index: int | None = None, right: bool | None = None, flip: bool | None = None) -> None:
    """Set the face shown in messages (it narrows the text area).

    Args:
        faceset: FaceSet image name, or None to remove the face.
        index: face in the image (0-15).
        right: show the face on the right side.
        flip: mirror the face.
    """


def message_options(
    transparent: bool = False,
    position: MessagePosition = "bottom",
    avoid_hero: bool = False,
    continue_events: bool = False,
) -> None:
    """Message window settings.

    Args:
        transparent: no window background.
        position: top, middle or bottom of the screen.
        avoid_hero: move the window so it never hides the hero (overrides position).
        continue_events: let other events run while a message is shown.
    """


def show_choices(*options: str, cancel: CancelOption | None = None, summary: str | None = None) -> str:
    """Show Choices (up to 4), written as a match statement::

        match show_choices("Yes", "No"):
            case "Yes": ...
            case "No": ...
            case _: ...      # optional: separate cancel branch

    When two options have the same text, the cases are the option
    numbers (``case 0:``, ``case 1:``).

    Args:
        options: the texts of the choices.
        cancel: the option (1-4) chosen with the cancel key; None forbids
            cancelling, a ``case _:`` adds a separate cancel branch.
        summary: editor summary of the options, when it differs from the texts.
    """
    return ""


# ==========================================================================
# Party, heroes, items
# ==========================================================================

ActorTarget = Actor | Party
"""``party`` (every hero of the party), ``actors[id]`` or ``actors[variables[id]]``."""


def change_exp(actor: ActorTarget, amount: Number, message: bool = False) -> None:
    """Change Experience: ``change_exp(actors[1], 500)``, ``change_exp(party, -variables[3])``.

    Args:
        message: show the level-up message.
    """


def change_level(actor: ActorTarget, amount: Number, message: bool = False) -> None:
    """Change Level: ``change_level(party, 1, message=True)`` (negative lowers it)."""


def change_stat(actor: ActorTarget, stat: Stat, amount: Number) -> None:
    """Permanently change a base stat: ``change_stat(actors[1], "attack", 5)``."""


def change_hp(actor: ActorTarget, amount: Number, lethal: bool | None = None) -> None:
    """Change HP (negative = damage).  Damage stops at 1 HP unless ``lethal=True``."""


def change_sp(actor: ActorTarget, amount: Number) -> None:
    """Change SP (negative = lose)."""


def full_heal(actor: ActorTarget) -> None:
    """Restore all HP and SP and cure all states."""


def learn_skill(actor: ActorTarget, skill: Number) -> None:
    """Teach a skill."""


def forget_skill(actor: ActorTarget, skill: Number) -> None:
    """Remove a skill."""


def equip(actor: ActorTarget, item: Number) -> None:
    """Equip an item (taken from the inventory)."""


def unequip(actor: ActorTarget, slot: EquipSlot, p4: int | None = None) -> None:
    """Remove equipment from one slot or all of them."""


def add_state(actor: ActorTarget, state: int) -> None:
    """Inflict a state (dead, poison, sleep...)."""


def remove_state(actor: ActorTarget, state: int) -> None:
    """Cure a state."""


def simulate_attack(
    actor: ActorTarget,
    attack: int | None = None,
    defense: int | None = None,
    spirit: int | None = None,
    variance: int | None = None,
    store_damage: Variable | None = None,
    use_store_damage: bool | None = None,
) -> None:
    """Simulated Attack: deal damage as if attacked by an invisible enemy
    (can cause a game over).

    Args:
        attack, defense, spirit: weights of the damage formula.
        variance: random variation (0-10).
        store_damage: also store the damage in this variable.
    """


def change_class(
    actor: ActorTarget,
    class_id: int,
    reset_level: bool | None = None,
    skills: SkillMode | None = None,
    stats: StatMode | None = None,
    message: bool | None = None,
) -> None:
    """Change Class (2003): also changes base stats and battle commands.

    Args:
        class_id: new class (0 = none).
        reset_level: back to level 1.
        skills: keep, replace with the class skills, or add them.
        stats: keep, halve, as at level 1, or as at the current level.
        message: show the learned-skills message.
    """


def add_battle_command(actor: ActorTarget, command: int) -> None:
    """Add a battle command to the hero's menu (2003)."""


def remove_battle_command(actor: ActorTarget, command: int) -> None:
    """Remove a battle command (2003); command 0 removes all."""


def enter_hero_name(actor: int, charset: int | None = None, use_current_name: bool | None = None) -> None:
    """Open the name entry screen.

    Args:
        actor: hero id.
        charset: letter set of the entry screen.
        use_current_name: start from the current name instead of an empty one.
    """


# ==========================================================================
# System
# ==========================================================================


def set_system_bgm(
    context: BgmContext,
    name: str,
    fade: int | None = None,
    volume: int | None = None,
    tempo: int | None = None,
    balance: int | None = None,
) -> None:
    """Change a system music (battle, victory, inn, vehicles, game over)."""


def set_system_se(
    context: SeContext, name: str, volume: int | None = None, tempo: int | None = None, balance: int | None = None
) -> None:
    """Change a system sound effect (cursor, decision, ...)."""


def set_system_graphics(
    name: str, stretch: Literal["stretch", "tile"] | None = None, font: Literal["gothic", "mincho"] | None = None
) -> None:
    """Change the System graphic (windows, cursor, text colours)."""


def set_transition(kind: TransitionKind, transition: Transition) -> None:
    """Change a default screen transition (teleport, battle start/end)."""


# ==========================================================================
# Map and movement
# ==========================================================================


def teleport(map: int, x: int, y: int, direction: TeleportDirection = "retain") -> None:
    """Teleport the party to another map position."""


def memorize_location(map: Variable, x: Variable, y: Variable) -> None:
    """Store the party's map id and position in three variables."""


def recall_location(map: Variable, x: Variable, y: Variable) -> None:
    """Teleport the party to a position stored with memorize_location()."""


def toggle_vehicle() -> None:
    """Get on / off the vehicle the hero faces."""


def set_vehicle_location(
    vehicle: Literal["party", "boat", "ship", "airship"],
    map: Number,
    x: Number,
    y: Number,
    direction: TeleportDirection | None = None,
) -> None:
    """Place a vehicle on a map (map, x and y: all numbers or all variables[id])."""


def swap_events(first: Character, second: Character) -> None:
    """Swap the positions of two events of the map."""


def set_tileset(chipset: int) -> None:
    """Change the map's chipset (tileset)."""


def set_panorama(
    name: str,
    scroll_x: bool | None = None,
    scroll_y: bool | None = None,
    auto_scroll_x: bool | None = None,
    speed_x: int | None = None,
    auto_scroll_y: bool | None = None,
    speed_y: int | None = None,
) -> None:
    """Change the panorama (parallax background) of the map."""


def set_encounter_rate(steps: int) -> None:
    """Average number of steps between random battles (0 = none)."""


def replace_tile(layer: Literal["lower", "upper"], old: int, new: int) -> None:
    """Replace every tile `old` by tile `new` on a layer of the map."""


def add_teleport_target(map: int, x: int, y: int, switch: int | None = None, use_switch: bool | None = None) -> None:
    """Add a destination for teleport skills (optionally turning a switch ON)."""


def remove_teleport_target(
    map: int, x: int | None = None, y: int | None = None, switch: int | None = None, use_switch: bool | None = None
) -> None:
    """Remove a teleport skill destination."""


def set_escape_target(map: int, x: int, y: int, switch: int | None = None, use_switch: bool | None = None) -> None:
    """Set where escape skills lead (optionally turning a switch ON)."""


def wait_for_movement() -> None:
    """Wait until all moving events finished their routes (except repeating ones)."""


def halt_all_movement() -> None:
    """Stop every event's movement."""


# ==========================================================================
# Screen
# ==========================================================================


def erase_screen(transition: Transition = "default") -> None:
    """Erase Screen: hide the map with a transition (effects done before
    show_screen() appear with it)."""


def show_screen(transition: Transition = "default") -> None:
    """Show Screen after erase_screen()."""


def tint_screen(
    red: int | None = None,
    green: int | None = None,
    blue: int | None = None,
    saturation: int | None = None,
    duration: float | None = None,
    wait: bool | None = None,
    extra: Extra = (),
) -> None:
    """Tint Screen: colour 0-200 per channel (100 = normal), over `duration` seconds."""


def flash_screen(
    red: int | None = None,
    green: int | None = None,
    blue: int | None = None,
    strength: int | None = None,
    duration: float | None = None,
    wait: bool | None = None,
    mode: FlashMode | None = None,
    extra: Extra = (),
) -> None:
    """Flash Screen: colour 0-31 per channel; mode begin/end repeats (2003)."""


def shake_screen(
    strength: int | None = None,
    speed: int | None = None,
    duration: float | None = None,
    wait: bool | None = None,
    mode: FlashMode | None = None,
    extra: Extra = (),
) -> None:
    """Shake Screen (strength and speed 1-9); mode begin/end shakes until stopped (2003)."""


def pan_screen(direction: Direction, distance: int, speed: int = 3, wait: bool = False) -> None:
    """Scroll the view by `distance` tiles away from the hero."""


def reset_screen_pan(speed: int = 3, wait: bool = False, direction: Direction = "up", distance: int = 0) -> None:
    """Scroll the view back to the hero."""


def lock_screen(direction: Direction = "up", distance: int = 0, speed: int = 0, wait: bool = False) -> None:
    """Lock the view: it stops following the hero."""


def unlock_screen(direction: Direction = "up", distance: int = 0, speed: int = 0, wait: bool = False) -> None:
    """Unlock the view: it follows the hero again."""


def weather(kind: WeatherKind, strength: Strength = "weak") -> None:
    """Weather effect: rain, snow, fog or sandstorm (2003), or none."""


# ==========================================================================
# Audio and video
# ==========================================================================


def play_bgm(name: str, fade: int = 0, volume: int = 100, tempo: int = 100, balance: int = 50) -> None:
    """Play a music of the Music folder (MIDI, WAV, MP3, OGG).

    Args:
        fade: fade-in in milliseconds.
        volume: 0-100.
        tempo: 50-150 (100 = normal speed).
        balance: 0 (left) - 100 (right), 50 = centre.
    """


def play_se(name: str, volume: int = 100, tempo: int = 100, balance: int = 50) -> MoveStep:
    """Play a sound effect of the Sound folder ("(OFF)" stops all sounds).
    RPG_RT plays at most 4 sounds at once.  Also usable as a move step."""
    return MoveStep()


def fade_out_bgm(seconds: float) -> None:
    """Fade the music out."""


def memorize_bgm() -> None:
    """Remember the current music."""


def play_memorized_bgm() -> None:
    """Play the music remembered with memorize_bgm()."""


def play_movie(
    name: str, *, x: Number = 0, y: Number = 0, width: int | None = None, height: int | None = None, extra: Extra = ()
) -> None:
    """Play a movie (.avi) of the Movie folder at a position and size."""


# ==========================================================================
# Flow and menus
# ==========================================================================


def wait(seconds: float = 0, key: bool = False) -> None:
    """Wait in steps of 0.1 s.  ``wait(0.0)`` still pauses for a moment;
    ``wait(key=True)`` waits for a key press (2003)."""


def label(id: int) -> None:
    """A jump target for goto(id); with duplicates only the first counts."""


def goto(id: int) -> None:
    """Jump to label(id)."""


def break_loop() -> None:
    """Break Loop outside a while loop (inside one, write ``break``)."""


def game_over() -> None:
    """Show the game over screen."""


def return_to_title() -> None:
    """Go back to the title screen."""


def open_save_menu() -> None:
    """Open the save screen."""


def open_main_menu() -> None:
    """Open the main menu."""


def open_load_menu() -> None:
    """Open the load screen (2003)."""


def exit_game() -> None:
    """Close the game (2003)."""


def toggle_fullscreen() -> None:
    """Switch between window and fullscreen (2003)."""


def toggle_atb_mode() -> None:
    """Switch the battle gauge between active and wait modes (2003)."""


def open_video_options() -> None:
    """Open the video / settings menu (2003; EasyRPG settings menu)."""


# ==========================================================================
# Battles, shops, inns
# ==========================================================================


def start_battle(
    troop: Number,
    *,
    background: Literal["map", "image", "terrain"] | None = None,
    escape: Literal["disallow", "end_event", "branch"] | None = None,
    defeat: Literal["game_over", "branch"] | None = None,
    first_strike: bool | None = None,
    condition: Literal["none", "initiative", "back_attack", "surround", "pincer"] | None = None,
    formation: Literal["terrain", "loose", "tight"] | None = None,
    terrain: int | None = None,
    image: str | None = None,
    extra: Extra = (),
) -> str:
    """Start a battle.  With branches, write it as a match::

        match start_battle(3, escape="branch", defeat="branch"):
            case "victory": ...
            case "escape": ...
            case "defeat": ...

    Args:
        troop: troop id.
        background: from the map, an image (``image=``), or a terrain (``terrain=``).
        escape: forbid escaping, end the event on escape, or an "escape" branch.
        defeat: game over, or a "defeat" branch.
        first_strike: the party attacks first.
        condition, formation: battle start condition and formation (2003).
    """
    return ""


def open_shop(
    items: list[int],
    *,
    mode: Literal["buy_sell", "buy", "sell"] | None = None,
    style: int | None = None,
    branches: bool | None = None,
    p3: int | None = None,
    extra: Extra = (),
) -> str:
    """Open a shop selling `items`.  For branches use
    ``match open_shop([...]):`` with ``case "bought":`` / ``case "not_bought":``.

    Args:
        mode: buy and sell, buy only or sell only.
        style: shop message set (0-2).
    """
    return ""


def inn(price: int, *, style: int | None = None, branches: bool | None = None, extra: Extra = ()) -> str:
    """Offer a night at the inn.  For branches use ``match inn(50):`` with
    ``case "stayed":`` / ``case "declined":``.

    Args:
        price: price in gold.
        style: inn message set (0-1).
    """
    return ""


def set_battle_background(name: str) -> None:
    """Change the battle background (in battle)."""


def show_battle_animation(animation: int, target: int, wait: bool | None = None, allies: bool | None = None) -> None:
    """Show a battle animation on an enemy (in battle; 2003 can target allies)."""


def end_battle() -> None:
    """End the current battle."""


def battle_call_common_event(common_event: int) -> None:
    """Call a common event from a battle (2003)."""


def force_flee(
    who: Literal["party", "all_enemies", "enemy"], enemy: int | None = None, ignore_conditions: bool | None = None
) -> None:
    """Make the party or enemies flee (2003)."""


def enable_combo(actor: int, command: int, times: int) -> None:
    """Let a hero use a battle command several times per turn (2003)."""


# ==========================================================================
# Generic command
# ==========================================================================


def cmd(
    code: int | CommandName, *params: int, text: str = "", indent: int | None = None
) -> AbstractContextManager[None]:
    """Any event command by code or name with its raw parameters, e.g.
    ``cmd("TintScreen", 100, 100, 100, 100, 20, 1)``.  ``with cmd(...):``
    opens a block for commands that have one.  rpgsync uses it only for
    patch commands (Maniac, EasyRPG) and unusual data."""
    return nullcontext()
