"""An RPG Maker 2000/2003 project folder and its script folder."""

from __future__ import annotations

import configparser
import glob
import json
import os
import re

from .commands import Ctx
from .lcf import LcfFile, read_map_tree_names

# Windows code pages used by RPG Maker games, as Python codec names.
CODEPAGES = {
    "932": "cp932",
    "936": "gbk",
    "949": "cp949",
    "950": "cp950",
    "1250": "cp1250",
    "1251": "cp1251",
    "1252": "cp1252",
    "1253": "cp1253",
    "1254": "cp1254",
    "1255": "cp1255",
    "1256": "cp1256",
    "1257": "cp1257",
    "1258": "cp1258",
    "874": "cp874",
}

CONFIG_DIR = ".rpgsync"


def _stat(path: str) -> tuple[int, int] | None:
    try:
        st = os.stat(path)
    except OSError:
        return None
    return (st.st_mtime_ns, st.st_size)


class Project:
    def __init__(self, game_dir: str, script_dir: str | None = None, encoding: str | None = None):
        self.game_dir = os.path.abspath(game_dir)
        if not os.path.exists(os.path.join(self.game_dir, "RPG_RT.ldb")):
            raise SystemExit("%s is not an RPG Maker 2000/2003 project (no RPG_RT.ldb)" % self.game_dir)
        self.script_dir = os.path.abspath(script_dir or os.path.join(self.game_dir, "Scripts"))
        self.state_dir = os.path.join(self.script_dir, CONFIG_DIR)
        os.makedirs(self.state_dir, exist_ok=True)
        cfg = self._load_config()
        self.encoding = encoding or cfg.get("encoding") or self.detect_encoding()
        "x".encode(self.encoding)  # validate codec name early
        if cfg.get("encoding") != self.encoding:
            cfg["encoding"] = self.encoding
            self._save_config(cfg)
        self._ctx: Ctx | None = None
        self._ldb_stat: tuple[int, int] | None = None
        self._handles_key: tuple | None = None
        names = os.path.join(self.script_dir, "database", "names.py")  # generated by an older rpgsync
        if os.path.exists(names):
            with open(names, encoding="utf-8") as f:
                if "(generated by rpgsync from RPG_RT.ldb, do not edit)" in f.readline():
                    os.remove(names)
        old = os.path.join(self.script_dir, "CommonEvents.py")  # before rpgsync put it in database/
        if os.path.exists(old) and not os.path.exists(self.common_events_script):
            os.makedirs(os.path.dirname(self.common_events_script), exist_ok=True)
            os.replace(old, self.common_events_script)

    # -- paths ---------------------------------------------------------------
    @property
    def ldb_path(self) -> str:
        return os.path.join(self.game_dir, "RPG_RT.ldb")

    def map_paths(self) -> dict[int, str]:
        out = {}
        for p in glob.glob(os.path.join(self.game_dir, "*")):
            m = re.fullmatch(r"map(\d{4})\.lmu", os.path.basename(p), re.I)
            if m:
                out[int(m.group(1))] = p
        return dict(sorted(out.items()))

    def script_for_map(self, map_id: int) -> str:
        return os.path.join(self.script_dir, "Map%04d.py" % map_id)

    @property
    def common_events_script(self) -> str:
        return os.path.join(self.script_dir, "database", "common_events.py")

    # -- config ----------------------------------------------------------------
    def _load_config(self) -> dict:
        try:
            with open(os.path.join(self.state_dir, "config.json")) as f:
                return json.load(f)
        except (OSError, ValueError):
            return {}

    def _save_config(self, cfg: dict) -> None:
        with open(os.path.join(self.state_dir, "config.json"), "w") as f:
            json.dump(cfg, f, indent=2)

    # -- encoding ----------------------------------------------------------------
    def detect_encoding(self) -> str:
        ini = os.path.join(self.game_dir, "RPG_RT.ini")
        if os.path.exists(ini):
            cp = configparser.ConfigParser(strict=False, interpolation=None)
            try:
                cp.read(ini, encoding="latin-1")
                for section in ("EasyRPG", "RPG_RT"):
                    if cp.has_option(section, "Encoding"):
                        v = cp.get(section, "Encoding").strip()
                        return CODEPAGES.get(v, v)
            except configparser.Error:
                pass
        # Heuristic: Japanese text decodes as Shift-JIS and contains kana/kanji.
        sample = b""
        lmt = os.path.join(self.game_dir, "RPG_RT.lmt")
        if os.path.exists(lmt):
            sample += b"".join(read_map_tree_names(lmt).values())
        with open(self.ldb_path, "rb") as f:
            sample += f.read(200000)
        nonascii = re.findall(rb"[\x80-\xff][\x40-\xff]", sample)
        if len(nonascii) > 20:
            try:
                text = b"".join(nonascii).decode("cp932")
                jp = sum(1 for ch in text if "぀" <= ch <= "ヿ" or "一" <= ch <= "鿿")
                if jp > len(text) * 0.6:
                    return "cp932"
            except UnicodeDecodeError:
                pass
        return "cp1252"

    # -- database context ----------------------------------------------------------
    def context(self, refresh: bool = False) -> Ctx:
        stat = os.stat(self.ldb_path)
        if (stat.st_mtime_ns, stat.st_size) != self._ldb_stat:
            refresh = True  # changed in the editor or by a sync: names may have changed
            self._ldb_stat = (stat.st_mtime_ns, stat.st_size)
        if self._ctx is None or refresh:
            ctx = Ctx(encoding=self.encoding)
            db = LcfFile.load(self.ldb_path).root
            ctx.engine = "2k3" if (db._chunk(0x1D) is not None or db._chunk(0x1E) is not None) else "2k"
            for key in ("switches", "variables", "items", "actors", "commonevents"):
                ctx.names[key] = {it.id: ctx.dec(it.struct.get("name")) for it in db.get(key) if it.struct.get("name")}
            ctx.choice_sep = self.choice_separator()
            self._ctx = ctx
            self._handles_key = None
        # names of variables / switches: the attributes of their database files
        key = (*(_stat(self.table_script(t)) for t in ("variables", "switches")), _stat(self.common_events_script))
        if key != self._handles_key:
            self._ctx.handles = self._handles(self._ctx)
            self._handles_key = key
        return self._ctx

    def table_script(self, table: str) -> str:
        return os.path.join(self.script_dir, "database", table + ".py")

    def _handles(self, ctx: Ctx) -> dict[str, dict[int, str]]:
        from .database import identifiers, read_identifiers

        out = {}
        for table in ("variables", "switches"):
            try:
                with open(self.table_script(table), encoding="utf-8") as f:
                    keep = read_identifiers(f.read())
            except OSError:
                keep = {}
            out[table] = identifiers(table, ctx.names.get(table, {}), keep)
        out["common_events"] = self._common_event_names()
        return out

    def _common_event_names(self) -> dict[int, str]:
        """Function names of the common events: the ones in common_events.py,
        else derived from the editor names."""
        from .lcf import LcfFile
        from .script import _ce_names, common_event_names, read_function_names

        try:
            with open(self.common_events_script, encoding="utf-8") as f:
                keep = read_function_names(f.read())
        except OSError:
            keep = {}
        assert self._ctx is not None
        return common_event_names(_ce_names(LcfFile.load(self.ldb_path).root, self._ctx), keep)

    def choice_separator(self) -> str | None:
        """Detected once per game, then kept in .rpgsync/config.json."""
        cfg = self._load_config()
        if "choice_separator" not in cfg:
            from .script import detect_choice_sep

            cfg["choice_separator"] = detect_choice_sep(self.map_paths().values())
            self._save_config(cfg)
        return cfg["choice_separator"]

    def map_names(self) -> dict[int, str]:
        lmt = os.path.join(self.game_dir, "RPG_RT.lmt")
        if not os.path.exists(lmt):
            return {}
        return {k: v.decode(self.encoding, errors="replace") for k, v in read_map_tree_names(lmt).items()}
